/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Feed Pipe API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DailyPlan,
  DietRecommendations,
  PatchedDailyPlan,
  PatchedProfile,
  Profile,
  ProfileUpdateDailyPlanPartialUpdate400,
  ProfileUpdateDailyPlanUpdate400,
} from "../feedPipeAPI.schemas";

import { axiosInstance } from "../../../../axios/axios";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type profileListResponse200 = {
  data: Profile[];
  status: 200;
};

export type profileListResponseSuccess = profileListResponse200 & {
  headers: Headers;
};
export type profileListResponse = profileListResponseSuccess;

export const getProfileListUrl = () => {
  return `/api/profile/`;
};

export const profileList = async (
  options?: RequestInit,
): Promise<profileListResponse> => {
  return axiosInstance<profileListResponse>(getProfileListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getProfileListQueryKey = () => {
  return [`/api/profile/`] as const;
};

export const getProfileListQueryOptions = <
  TData = Awaited<ReturnType<typeof profileList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof profileList>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileList>>> = ({
    signal,
  }) => profileList({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileListQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileList>>
>;
export type ProfileListQueryError = unknown;

export function useProfileList<
  TData = Awaited<ReturnType<typeof profileList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileList>>,
          TError,
          Awaited<ReturnType<typeof profileList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileList<
  TData = Awaited<ReturnType<typeof profileList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileList>>,
          TError,
          Awaited<ReturnType<typeof profileList>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileList<
  TData = Awaited<ReturnType<typeof profileList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProfileList<
  TData = Awaited<ReturnType<typeof profileList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type profileCreateResponse201 = {
  data: Profile;
  status: 201;
};

export type profileCreateResponseSuccess = profileCreateResponse201 & {
  headers: Headers;
};
export type profileCreateResponse = profileCreateResponseSuccess;

export const getProfileCreateUrl = () => {
  return `/api/profile/`;
};

export const profileCreate = async (
  profile: NonReadonly<Profile>,
  options?: RequestInit,
): Promise<profileCreateResponse> => {
  return axiosInstance<profileCreateResponse>(getProfileCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(profile),
  });
};

export const getProfileCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCreate>>,
    TError,
    { data: NonReadonly<Profile> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCreate>>,
  TError,
  { data: NonReadonly<Profile> },
  TContext
> => {
  const mutationKey = ["profileCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCreate>>,
    { data: NonReadonly<Profile> }
  > = (props) => {
    const { data } = props ?? {};

    return profileCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCreate>>
>;
export type ProfileCreateMutationBody = NonReadonly<Profile>;
export type ProfileCreateMutationError = unknown;

export const useProfileCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCreate>>,
      TError,
      { data: NonReadonly<Profile> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCreate>>,
  TError,
  { data: NonReadonly<Profile> },
  TContext
> => {
  return useMutation(getProfileCreateMutationOptions(options), queryClient);
};
export type profileRetrieveResponse200 = {
  data: Profile;
  status: 200;
};

export type profileRetrieveResponseSuccess = profileRetrieveResponse200 & {
  headers: Headers;
};
export type profileRetrieveResponse = profileRetrieveResponseSuccess;

export const getProfileRetrieveUrl = (id: string) => {
  return `/api/profile/${id}/`;
};

export const profileRetrieve = async (
  id: string,
  options?: RequestInit,
): Promise<profileRetrieveResponse> => {
  return axiosInstance<profileRetrieveResponse>(getProfileRetrieveUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getProfileRetrieveQueryKey = (id?: string) => {
  return [`/api/profile/${id}/`] as const;
};

export const getProfileRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof profileRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileRetrieveQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileRetrieve>>> = ({
    signal,
  }) => profileRetrieve(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profileRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileRetrieve>>
>;
export type ProfileRetrieveQueryError = unknown;

export function useProfileRetrieve<
  TData = Awaited<ReturnType<typeof profileRetrieve>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileRetrieve>>,
          TError,
          Awaited<ReturnType<typeof profileRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileRetrieve<
  TData = Awaited<ReturnType<typeof profileRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileRetrieve>>,
          TError,
          Awaited<ReturnType<typeof profileRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileRetrieve<
  TData = Awaited<ReturnType<typeof profileRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProfileRetrieve<
  TData = Awaited<ReturnType<typeof profileRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type profileUpdateResponse200 = {
  data: Profile;
  status: 200;
};

export type profileUpdateResponseSuccess = profileUpdateResponse200 & {
  headers: Headers;
};
export type profileUpdateResponse = profileUpdateResponseSuccess;

export const getProfileUpdateUrl = (id: string) => {
  return `/api/profile/${id}/`;
};

export const profileUpdate = async (
  id: string,
  profile: NonReadonly<Profile>,
  options?: RequestInit,
): Promise<profileUpdateResponse> => {
  return axiosInstance<profileUpdateResponse>(getProfileUpdateUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(profile),
  });
};

export const getProfileUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileUpdate>>,
    TError,
    { id: string; data: NonReadonly<Profile> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileUpdate>>,
  TError,
  { id: string; data: NonReadonly<Profile> },
  TContext
> => {
  const mutationKey = ["profileUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileUpdate>>,
    { id: string; data: NonReadonly<Profile> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profileUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileUpdate>>
>;
export type ProfileUpdateMutationBody = NonReadonly<Profile>;
export type ProfileUpdateMutationError = unknown;

export const useProfileUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileUpdate>>,
      TError,
      { id: string; data: NonReadonly<Profile> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileUpdate>>,
  TError,
  { id: string; data: NonReadonly<Profile> },
  TContext
> => {
  return useMutation(getProfileUpdateMutationOptions(options), queryClient);
};
export type profilePartialUpdateResponse200 = {
  data: Profile;
  status: 200;
};

export type profilePartialUpdateResponseSuccess =
  profilePartialUpdateResponse200 & {
    headers: Headers;
  };
export type profilePartialUpdateResponse = profilePartialUpdateResponseSuccess;

export const getProfilePartialUpdateUrl = (id: string) => {
  return `/api/profile/${id}/`;
};

export const profilePartialUpdate = async (
  id: string,
  patchedProfile: NonReadonly<PatchedProfile>,
  options?: RequestInit,
): Promise<profilePartialUpdateResponse> => {
  return axiosInstance<profilePartialUpdateResponse>(
    getProfilePartialUpdateUrl(id),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(patchedProfile),
    },
  );
};

export const getProfilePartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profilePartialUpdate>>,
    TError,
    { id: string; data: NonReadonly<PatchedProfile> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profilePartialUpdate>>,
  TError,
  { id: string; data: NonReadonly<PatchedProfile> },
  TContext
> => {
  const mutationKey = ["profilePartialUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profilePartialUpdate>>,
    { id: string; data: NonReadonly<PatchedProfile> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profilePartialUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfilePartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profilePartialUpdate>>
>;
export type ProfilePartialUpdateMutationBody = NonReadonly<PatchedProfile>;
export type ProfilePartialUpdateMutationError = unknown;

export const useProfilePartialUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profilePartialUpdate>>,
      TError,
      { id: string; data: NonReadonly<PatchedProfile> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profilePartialUpdate>>,
  TError,
  { id: string; data: NonReadonly<PatchedProfile> },
  TContext
> => {
  return useMutation(
    getProfilePartialUpdateMutationOptions(options),
    queryClient,
  );
};
export type profileDestroyResponse204 = {
  data: void;
  status: 204;
};

export type profileDestroyResponseSuccess = profileDestroyResponse204 & {
  headers: Headers;
};
export type profileDestroyResponse = profileDestroyResponseSuccess;

export const getProfileDestroyUrl = (id: string) => {
  return `/api/profile/${id}/`;
};

export const profileDestroy = async (
  id: string,
  options?: RequestInit,
): Promise<profileDestroyResponse> => {
  return axiosInstance<profileDestroyResponse>(getProfileDestroyUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getProfileDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileDestroy>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileDestroy>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["profileDestroy"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileDestroy>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return profileDestroy(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileDestroy>>
>;

export type ProfileDestroyMutationError = unknown;

export const useProfileDestroy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileDestroy>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileDestroy>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getProfileDestroyMutationOptions(options), queryClient);
};
/**
 * Get recommendations for the daily plan.
 */
export type profileGetDailyPlanRecommendationsRetrieveResponse200 = {
  data: DietRecommendations;
  status: 200;
};

export type profileGetDailyPlanRecommendationsRetrieveResponseSuccess =
  profileGetDailyPlanRecommendationsRetrieveResponse200 & {
    headers: Headers;
  };
export type profileGetDailyPlanRecommendationsRetrieveResponse =
  profileGetDailyPlanRecommendationsRetrieveResponseSuccess;

export const getProfileGetDailyPlanRecommendationsRetrieveUrl = (
  id: string,
) => {
  return `/api/profile/${id}/get_daily_plan_recommendations/`;
};

export const profileGetDailyPlanRecommendationsRetrieve = async (
  id: string,
  options?: RequestInit,
): Promise<profileGetDailyPlanRecommendationsRetrieveResponse> => {
  return axiosInstance<profileGetDailyPlanRecommendationsRetrieveResponse>(
    getProfileGetDailyPlanRecommendationsRetrieveUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getProfileGetDailyPlanRecommendationsRetrieveQueryKey = (
  id?: string,
) => {
  return [`/api/profile/${id}/get_daily_plan_recommendations/`] as const;
};

export const getProfileGetDailyPlanRecommendationsRetrieveQueryOptions = <
  TData = Awaited<
    ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
  >,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileGetDailyPlanRecommendationsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>
  > = ({ signal }) =>
    profileGetDailyPlanRecommendationsRetrieve(id, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileGetDailyPlanRecommendationsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>
>;
export type ProfileGetDailyPlanRecommendationsRetrieveQueryError = unknown;

export function useProfileGetDailyPlanRecommendationsRetrieve<
  TData = Awaited<
    ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
  >,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
          >,
          TError,
          Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileGetDailyPlanRecommendationsRetrieve<
  TData = Awaited<
    ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
  >,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
          >,
          TError,
          Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileGetDailyPlanRecommendationsRetrieve<
  TData = Awaited<
    ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
  >,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProfileGetDailyPlanRecommendationsRetrieve<
  TData = Awaited<
    ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>
  >,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileGetDailyPlanRecommendationsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getProfileGetDailyPlanRecommendationsRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update or create the daily plan associated with the profile.
 */
export type profileUpdateDailyPlanUpdateResponse200 = {
  data: DailyPlan;
  status: 200;
};

export type profileUpdateDailyPlanUpdateResponse400 = {
  data: ProfileUpdateDailyPlanUpdate400;
  status: 400;
};

export type profileUpdateDailyPlanUpdateResponseSuccess =
  profileUpdateDailyPlanUpdateResponse200 & {
    headers: Headers;
  };
export type profileUpdateDailyPlanUpdateResponseError =
  profileUpdateDailyPlanUpdateResponse400 & {
    headers: Headers;
  };

export type profileUpdateDailyPlanUpdateResponse =
  | profileUpdateDailyPlanUpdateResponseSuccess
  | profileUpdateDailyPlanUpdateResponseError;

export const getProfileUpdateDailyPlanUpdateUrl = (id: string) => {
  return `/api/profile/${id}/update_daily_plan/`;
};

export const profileUpdateDailyPlanUpdate = async (
  id: string,
  dailyPlan: NonReadonly<DailyPlan>,
  options?: RequestInit,
): Promise<profileUpdateDailyPlanUpdateResponse> => {
  return axiosInstance<profileUpdateDailyPlanUpdateResponse>(
    getProfileUpdateDailyPlanUpdateUrl(id),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dailyPlan),
    },
  );
};

export const getProfileUpdateDailyPlanUpdateMutationOptions = <
  TError = ProfileUpdateDailyPlanUpdate400,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileUpdateDailyPlanUpdate>>,
    TError,
    { id: string; data: NonReadonly<DailyPlan> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileUpdateDailyPlanUpdate>>,
  TError,
  { id: string; data: NonReadonly<DailyPlan> },
  TContext
> => {
  const mutationKey = ["profileUpdateDailyPlanUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileUpdateDailyPlanUpdate>>,
    { id: string; data: NonReadonly<DailyPlan> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profileUpdateDailyPlanUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileUpdateDailyPlanUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileUpdateDailyPlanUpdate>>
>;
export type ProfileUpdateDailyPlanUpdateMutationBody = NonReadonly<DailyPlan>;
export type ProfileUpdateDailyPlanUpdateMutationError =
  ProfileUpdateDailyPlanUpdate400;

export const useProfileUpdateDailyPlanUpdate = <
  TError = ProfileUpdateDailyPlanUpdate400,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileUpdateDailyPlanUpdate>>,
      TError,
      { id: string; data: NonReadonly<DailyPlan> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileUpdateDailyPlanUpdate>>,
  TError,
  { id: string; data: NonReadonly<DailyPlan> },
  TContext
> => {
  return useMutation(
    getProfileUpdateDailyPlanUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * Update or create the daily plan associated with the profile.
 */
export type profileUpdateDailyPlanPartialUpdateResponse200 = {
  data: DailyPlan;
  status: 200;
};

export type profileUpdateDailyPlanPartialUpdateResponse400 = {
  data: ProfileUpdateDailyPlanPartialUpdate400;
  status: 400;
};

export type profileUpdateDailyPlanPartialUpdateResponseSuccess =
  profileUpdateDailyPlanPartialUpdateResponse200 & {
    headers: Headers;
  };
export type profileUpdateDailyPlanPartialUpdateResponseError =
  profileUpdateDailyPlanPartialUpdateResponse400 & {
    headers: Headers;
  };

export type profileUpdateDailyPlanPartialUpdateResponse =
  | profileUpdateDailyPlanPartialUpdateResponseSuccess
  | profileUpdateDailyPlanPartialUpdateResponseError;

export const getProfileUpdateDailyPlanPartialUpdateUrl = (id: string) => {
  return `/api/profile/${id}/update_daily_plan/`;
};

export const profileUpdateDailyPlanPartialUpdate = async (
  id: string,
  patchedDailyPlan: NonReadonly<PatchedDailyPlan>,
  options?: RequestInit,
): Promise<profileUpdateDailyPlanPartialUpdateResponse> => {
  return axiosInstance<profileUpdateDailyPlanPartialUpdateResponse>(
    getProfileUpdateDailyPlanPartialUpdateUrl(id),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(patchedDailyPlan),
    },
  );
};

export const getProfileUpdateDailyPlanPartialUpdateMutationOptions = <
  TError = ProfileUpdateDailyPlanPartialUpdate400,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileUpdateDailyPlanPartialUpdate>>,
    TError,
    { id: string; data: NonReadonly<PatchedDailyPlan> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileUpdateDailyPlanPartialUpdate>>,
  TError,
  { id: string; data: NonReadonly<PatchedDailyPlan> },
  TContext
> => {
  const mutationKey = ["profileUpdateDailyPlanPartialUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileUpdateDailyPlanPartialUpdate>>,
    { id: string; data: NonReadonly<PatchedDailyPlan> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profileUpdateDailyPlanPartialUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileUpdateDailyPlanPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileUpdateDailyPlanPartialUpdate>>
>;
export type ProfileUpdateDailyPlanPartialUpdateMutationBody =
  NonReadonly<PatchedDailyPlan>;
export type ProfileUpdateDailyPlanPartialUpdateMutationError =
  ProfileUpdateDailyPlanPartialUpdate400;

export const useProfileUpdateDailyPlanPartialUpdate = <
  TError = ProfileUpdateDailyPlanPartialUpdate400,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileUpdateDailyPlanPartialUpdate>>,
      TError,
      { id: string; data: NonReadonly<PatchedDailyPlan> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileUpdateDailyPlanPartialUpdate>>,
  TError,
  { id: string; data: NonReadonly<PatchedDailyPlan> },
  TContext
> => {
  return useMutation(
    getProfileUpdateDailyPlanPartialUpdateMutationOptions(options),
    queryClient,
  );
};
