/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Feed Pipe API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { Food, PatchedFood } from "../feedPipeAPI.schemas";

import { axiosInstance } from "../../../../axios/axios";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export type foodListResponse200 = {
  data: Food[];
  status: 200;
};

export type foodListResponseSuccess = foodListResponse200 & {
  headers: Headers;
};
export type foodListResponse = foodListResponseSuccess;

export const getFoodListUrl = () => {
  return `/api/food/`;
};

export const foodList = async (
  options?: RequestInit,
): Promise<foodListResponse> => {
  return axiosInstance<foodListResponse>(getFoodListUrl(), {
    ...options,
    method: "GET",
  });
};

export const getFoodListQueryKey = () => {
  return [`/api/food/`] as const;
};

export const getFoodListQueryOptions = <
  TData = Awaited<ReturnType<typeof foodList>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof foodList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFoodListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof foodList>>> = ({
    signal,
  }) => foodList({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof foodList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FoodListQueryResult = NonNullable<
  Awaited<ReturnType<typeof foodList>>
>;
export type FoodListQueryError = unknown;

export function useFoodList<
  TData = Awaited<ReturnType<typeof foodList>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof foodList>>,
          TError,
          Awaited<ReturnType<typeof foodList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFoodList<
  TData = Awaited<ReturnType<typeof foodList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof foodList>>,
          TError,
          Awaited<ReturnType<typeof foodList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFoodList<
  TData = Awaited<ReturnType<typeof foodList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFoodList<
  TData = Awaited<ReturnType<typeof foodList>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFoodListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type foodCreateResponse201 = {
  data: Food;
  status: 201;
};

export type foodCreateResponseSuccess = foodCreateResponse201 & {
  headers: Headers;
};
export type foodCreateResponse = foodCreateResponseSuccess;

export const getFoodCreateUrl = () => {
  return `/api/food/`;
};

export const foodCreate = async (
  food: NonReadonly<Food>,
  options?: RequestInit,
): Promise<foodCreateResponse> => {
  return axiosInstance<foodCreateResponse>(getFoodCreateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(food),
  });
};

export const getFoodCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof foodCreate>>,
    TError,
    { data: NonReadonly<Food> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof foodCreate>>,
  TError,
  { data: NonReadonly<Food> },
  TContext
> => {
  const mutationKey = ["foodCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof foodCreate>>,
    { data: NonReadonly<Food> }
  > = (props) => {
    const { data } = props ?? {};

    return foodCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FoodCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof foodCreate>>
>;
export type FoodCreateMutationBody = NonReadonly<Food>;
export type FoodCreateMutationError = unknown;

export const useFoodCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof foodCreate>>,
      TError,
      { data: NonReadonly<Food> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof foodCreate>>,
  TError,
  { data: NonReadonly<Food> },
  TContext
> => {
  return useMutation(getFoodCreateMutationOptions(options), queryClient);
};
export type foodRetrieveResponse200 = {
  data: Food;
  status: 200;
};

export type foodRetrieveResponseSuccess = foodRetrieveResponse200 & {
  headers: Headers;
};
export type foodRetrieveResponse = foodRetrieveResponseSuccess;

export const getFoodRetrieveUrl = (id: number) => {
  return `/api/food/${id}/`;
};

export const foodRetrieve = async (
  id: number,
  options?: RequestInit,
): Promise<foodRetrieveResponse> => {
  return axiosInstance<foodRetrieveResponse>(getFoodRetrieveUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getFoodRetrieveQueryKey = (id?: number) => {
  return [`/api/food/${id}/`] as const;
};

export const getFoodRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof foodRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodRetrieve>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFoodRetrieveQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof foodRetrieve>>> = ({
    signal,
  }) => foodRetrieve(id, { signal });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof foodRetrieve>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FoodRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof foodRetrieve>>
>;
export type FoodRetrieveQueryError = unknown;

export function useFoodRetrieve<
  TData = Awaited<ReturnType<typeof foodRetrieve>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodRetrieve>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof foodRetrieve>>,
          TError,
          Awaited<ReturnType<typeof foodRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFoodRetrieve<
  TData = Awaited<ReturnType<typeof foodRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodRetrieve>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof foodRetrieve>>,
          TError,
          Awaited<ReturnType<typeof foodRetrieve>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFoodRetrieve<
  TData = Awaited<ReturnType<typeof foodRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodRetrieve>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFoodRetrieve<
  TData = Awaited<ReturnType<typeof foodRetrieve>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof foodRetrieve>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFoodRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type foodUpdateResponse200 = {
  data: Food;
  status: 200;
};

export type foodUpdateResponseSuccess = foodUpdateResponse200 & {
  headers: Headers;
};
export type foodUpdateResponse = foodUpdateResponseSuccess;

export const getFoodUpdateUrl = (id: number) => {
  return `/api/food/${id}/`;
};

export const foodUpdate = async (
  id: number,
  food: NonReadonly<Food>,
  options?: RequestInit,
): Promise<foodUpdateResponse> => {
  return axiosInstance<foodUpdateResponse>(getFoodUpdateUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(food),
  });
};

export const getFoodUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof foodUpdate>>,
    TError,
    { id: number; data: NonReadonly<Food> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof foodUpdate>>,
  TError,
  { id: number; data: NonReadonly<Food> },
  TContext
> => {
  const mutationKey = ["foodUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof foodUpdate>>,
    { id: number; data: NonReadonly<Food> }
  > = (props) => {
    const { id, data } = props ?? {};

    return foodUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FoodUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof foodUpdate>>
>;
export type FoodUpdateMutationBody = NonReadonly<Food>;
export type FoodUpdateMutationError = unknown;

export const useFoodUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof foodUpdate>>,
      TError,
      { id: number; data: NonReadonly<Food> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof foodUpdate>>,
  TError,
  { id: number; data: NonReadonly<Food> },
  TContext
> => {
  return useMutation(getFoodUpdateMutationOptions(options), queryClient);
};
export type foodPartialUpdateResponse200 = {
  data: Food;
  status: 200;
};

export type foodPartialUpdateResponseSuccess = foodPartialUpdateResponse200 & {
  headers: Headers;
};
export type foodPartialUpdateResponse = foodPartialUpdateResponseSuccess;

export const getFoodPartialUpdateUrl = (id: number) => {
  return `/api/food/${id}/`;
};

export const foodPartialUpdate = async (
  id: number,
  patchedFood: NonReadonly<PatchedFood>,
  options?: RequestInit,
): Promise<foodPartialUpdateResponse> => {
  return axiosInstance<foodPartialUpdateResponse>(getFoodPartialUpdateUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(patchedFood),
  });
};

export const getFoodPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof foodPartialUpdate>>,
    TError,
    { id: number; data: NonReadonly<PatchedFood> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof foodPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedFood> },
  TContext
> => {
  const mutationKey = ["foodPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof foodPartialUpdate>>,
    { id: number; data: NonReadonly<PatchedFood> }
  > = (props) => {
    const { id, data } = props ?? {};

    return foodPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FoodPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof foodPartialUpdate>>
>;
export type FoodPartialUpdateMutationBody = NonReadonly<PatchedFood>;
export type FoodPartialUpdateMutationError = unknown;

export const useFoodPartialUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof foodPartialUpdate>>,
      TError,
      { id: number; data: NonReadonly<PatchedFood> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof foodPartialUpdate>>,
  TError,
  { id: number; data: NonReadonly<PatchedFood> },
  TContext
> => {
  return useMutation(getFoodPartialUpdateMutationOptions(options), queryClient);
};
export type foodDestroyResponse204 = {
  data: void;
  status: 204;
};

export type foodDestroyResponseSuccess = foodDestroyResponse204 & {
  headers: Headers;
};
export type foodDestroyResponse = foodDestroyResponseSuccess;

export const getFoodDestroyUrl = (id: number) => {
  return `/api/food/${id}/`;
};

export const foodDestroy = async (
  id: number,
  options?: RequestInit,
): Promise<foodDestroyResponse> => {
  return axiosInstance<foodDestroyResponse>(getFoodDestroyUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getFoodDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof foodDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof foodDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["foodDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof foodDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return foodDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type FoodDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof foodDestroy>>
>;

export type FoodDestroyMutationError = unknown;

export const useFoodDestroy = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof foodDestroy>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof foodDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getFoodDestroyMutationOptions(options), queryClient);
};
