/**
 * Generated by orval v8.0.1 🍺
 * Do not edit manually.
 * Feed Pipe API
 * Your project description
 * OpenAPI spec version: 1.0.0
 */
/**
 * * `g` - grams
 * `oz` - ounce
 * `lb` - pounds
 * `cup` - cups
 * `mL` - mL
 * `L` - liters
 */
export type AmountUnitEnum =
  (typeof AmountUnitEnum)[keyof typeof AmountUnitEnum];

export const AmountUnitEnum = {
  g: "g",
  oz: "oz",
  lb: "lb",
  cup: "cup",
  mL: "mL",
  L: "L",
} as const;

export type BlankEnum = (typeof BlankEnum)[keyof typeof BlankEnum];

export const BlankEnum = {
  "": "",
} as const;

/**
 * * `AF` - Afghanistan
 * `AX` - Åland Islands
 * `AL` - Albania
 * `DZ` - Algeria
 * `AS` - American Samoa
 * `AD` - Andorra
 * `AO` - Angola
 * `AI` - Anguilla
 * `AQ` - Antarctica
 * `AG` - Antigua and Barbuda
 * `AR` - Argentina
 * `AM` - Armenia
 * `AW` - Aruba
 * `AU` - Australia
 * `AT` - Austria
 * `AZ` - Azerbaijan
 * `BS` - Bahamas (The)
 * `BH` - Bahrain
 * `BD` - Bangladesh
 * `BB` - Barbados
 * `BY` - Belarus
 * `BE` - Belgium
 * `BZ` - Belize
 * `BJ` - Benin
 * `BM` - Bermuda
 * `BT` - Bhutan
 * `BO` - Bolivia
 * `BQ` - Bonaire, Sint Eustatius and Saba
 * `BA` - Bosnia and Herzegovina
 * `BW` - Botswana
 * `BV` - Bouvet Island
 * `BR` - Brazil
 * `IO` - British Indian Ocean Territory
 * `BN` - Brunei
 * `BG` - Bulgaria
 * `BF` - Burkina Faso
 * `BI` - Burundi
 * `CV` - Cabo Verde
 * `KH` - Cambodia
 * `CM` - Cameroon
 * `CA` - Canada
 * `KY` - Cayman Islands
 * `CF` - Central African Republic
 * `TD` - Chad
 * `CL` - Chile
 * `CN` - China
 * `CX` - Christmas Island
 * `CC` - Cocos (Keeling) Islands
 * `CO` - Colombia
 * `KM` - Comoros
 * `CG` - Congo
 * `CK` - Cook Islands
 * `CR` - Costa Rica
 * `CI` - Côte d'Ivoire
 * `HR` - Croatia
 * `CU` - Cuba
 * `CW` - Curaçao
 * `CY` - Cyprus
 * `CZ` - Czechia
 * `CD` - Democratic Republic of the Congo
 * `DK` - Denmark
 * `DJ` - Djibouti
 * `DM` - Dominica
 * `DO` - Dominican Republic
 * `EC` - Ecuador
 * `EG` - Egypt
 * `SV` - El Salvador
 * `GQ` - Equatorial Guinea
 * `ER` - Eritrea
 * `EE` - Estonia
 * `SZ` - Eswatini
 * `ET` - Ethiopia
 * `FK` - Falkland Islands (Malvinas)
 * `FO` - Faroe Islands
 * `FJ` - Fiji
 * `FI` - Finland
 * `FR` - France
 * `GF` - French Guiana
 * `PF` - French Polynesia
 * `TF` - French Southern Territories
 * `GA` - Gabon
 * `GM` - Gambia
 * `GE` - Georgia
 * `DE` - Germany
 * `GH` - Ghana
 * `GI` - Gibraltar
 * `GR` - Greece
 * `GL` - Greenland
 * `GD` - Grenada
 * `GP` - Guadeloupe
 * `GU` - Guam
 * `GT` - Guatemala
 * `GG` - Guernsey
 * `GN` - Guinea
 * `GW` - Guinea-Bissau
 * `GY` - Guyana
 * `HT` - Haiti
 * `HM` - Heard Island and McDonald Islands
 * `HN` - Honduras
 * `HK` - Hong Kong
 * `HU` - Hungary
 * `IS` - Iceland
 * `IN` - India
 * `ID` - Indonesia
 * `IR` - Iran
 * `IQ` - Iraq
 * `IE` - Ireland
 * `IM` - Isle of Man
 * `IL` - Israel
 * `IT` - Italy
 * `JM` - Jamaica
 * `JP` - Japan
 * `JE` - Jersey
 * `JO` - Jordan
 * `KZ` - Kazakhstan
 * `KE` - Kenya
 * `KI` - Kiribati
 * `KW` - Kuwait
 * `KG` - Kyrgyzstan
 * `LA` - Laos
 * `LV` - Latvia
 * `LB` - Lebanon
 * `LS` - Lesotho
 * `LR` - Liberia
 * `LY` - Libya
 * `LI` - Liechtenstein
 * `LT` - Lithuania
 * `LU` - Luxembourg
 * `MO` - Macao
 * `MG` - Madagascar
 * `MW` - Malawi
 * `MY` - Malaysia
 * `MV` - Maldives
 * `ML` - Mali
 * `MT` - Malta
 * `MH` - Marshall Islands
 * `MQ` - Martinique
 * `MR` - Mauritania
 * `MU` - Mauritius
 * `YT` - Mayotte
 * `MX` - Mexico
 * `FM` - Micronesia
 * `MD` - Moldova
 * `MC` - Monaco
 * `MN` - Mongolia
 * `ME` - Montenegro
 * `MS` - Montserrat
 * `MA` - Morocco
 * `MZ` - Mozambique
 * `MM` - Myanmar
 * `NA` - Namibia
 * `NR` - Nauru
 * `NP` - Nepal
 * `NL` - Netherlands
 * `NC` - New Caledonia
 * `NZ` - New Zealand
 * `NI` - Nicaragua
 * `NE` - Niger
 * `NG` - Nigeria
 * `NU` - Niue
 * `NF` - Norfolk Island
 * `KP` - North Korea
 * `MK` - North Macedonia
 * `MP` - Northern Mariana Islands
 * `NO` - Norway
 * `OM` - Oman
 * `PK` - Pakistan
 * `PW` - Palau
 * `PS` - Palestine
 * `PA` - Panama
 * `PG` - Papua New Guinea
 * `PY` - Paraguay
 * `PE` - Peru
 * `PH` - Philippines
 * `PN` - Pitcairn
 * `PL` - Poland
 * `PT` - Portugal
 * `PR` - Puerto Rico
 * `QA` - Qatar
 * `RE` - Réunion
 * `RO` - Romania
 * `RU` - Russia
 * `RW` - Rwanda
 * `BL` - Saint Barthélemy
 * `SH` - Saint Helena
 * `KN` - Saint Kitts and Nevis
 * `LC` - Saint Lucia
 * `MF` - Saint Martin (French part)
 * `PM` - Saint Pierre and Miquelon
 * `VC` - Saint Vincent and the Grenadines
 * `WS` - Samoa
 * `SM` - San Marino
 * `ST` - Sao Tome and Principe
 * `SA` - Saudi Arabia
 * `SN` - Senegal
 * `RS` - Serbia
 * `SC` - Seychelles
 * `SL` - Sierra Leone
 * `SG` - Singapore
 * `SX` - Sint Maarten (Dutch part)
 * `SK` - Slovakia
 * `SI` - Slovenia
 * `SB` - Solomon Islands
 * `SO` - Somalia
 * `ZA` - South Africa
 * `GS` - South Georgia
 * `KR` - South Korea
 * `SS` - South Sudan
 * `ES` - Spain
 * `LK` - Sri Lanka
 * `SD` - Sudan
 * `SR` - Suriname
 * `SJ` - Svalbard and Jan Mayen
 * `SE` - Sweden
 * `CH` - Switzerland
 * `SY` - Syria
 * `TW` - Taiwan
 * `TJ` - Tajikistan
 * `TZ` - Tanzania
 * `TH` - Thailand
 * `TL` - Timor-Leste
 * `TG` - Togo
 * `TK` - Tokelau
 * `TO` - Tonga
 * `TT` - Trinidad and Tobago
 * `TN` - Tunisia
 * `TR` - Türkiye
 * `TM` - Turkmenistan
 * `TC` - Turks and Caicos Islands
 * `TV` - Tuvalu
 * `UG` - Uganda
 * `UA` - Ukraine
 * `AE` - United Arab Emirates
 * `GB` - United Kingdom
 * `UM` - United States Minor Outlying Islands
 * `US` - United States of America
 * `UY` - Uruguay
 * `UZ` - Uzbekistan
 * `VU` - Vanuatu
 * `VA` - Vatican City
 * `VE` - Venezuela
 * `VN` - Vietnam
 * `VG` - Virgin Islands (British)
 * `VI` - Virgin Islands (U.S.)
 * `WF` - Wallis and Futuna
 * `EH` - Western Sahara
 * `YE` - Yemen
 * `ZM` - Zambia
 * `ZW` - Zimbabwe
 */
export type CountryEnum = (typeof CountryEnum)[keyof typeof CountryEnum];

export const CountryEnum = {
  AF: "AF",
  AX: "AX",
  AL: "AL",
  DZ: "DZ",
  AS: "AS",
  AD: "AD",
  AO: "AO",
  AI: "AI",
  AQ: "AQ",
  AG: "AG",
  AR: "AR",
  AM: "AM",
  AW: "AW",
  AU: "AU",
  AT: "AT",
  AZ: "AZ",
  BS: "BS",
  BH: "BH",
  BD: "BD",
  BB: "BB",
  BY: "BY",
  BE: "BE",
  BZ: "BZ",
  BJ: "BJ",
  BM: "BM",
  BT: "BT",
  BO: "BO",
  BQ: "BQ",
  BA: "BA",
  BW: "BW",
  BV: "BV",
  BR: "BR",
  IO: "IO",
  BN: "BN",
  BG: "BG",
  BF: "BF",
  BI: "BI",
  CV: "CV",
  KH: "KH",
  CM: "CM",
  CA: "CA",
  KY: "KY",
  CF: "CF",
  TD: "TD",
  CL: "CL",
  CN: "CN",
  CX: "CX",
  CC: "CC",
  CO: "CO",
  KM: "KM",
  CG: "CG",
  CK: "CK",
  CR: "CR",
  CI: "CI",
  HR: "HR",
  CU: "CU",
  CW: "CW",
  CY: "CY",
  CZ: "CZ",
  CD: "CD",
  DK: "DK",
  DJ: "DJ",
  DM: "DM",
  DO: "DO",
  EC: "EC",
  EG: "EG",
  SV: "SV",
  GQ: "GQ",
  ER: "ER",
  EE: "EE",
  SZ: "SZ",
  ET: "ET",
  FK: "FK",
  FO: "FO",
  FJ: "FJ",
  FI: "FI",
  FR: "FR",
  GF: "GF",
  PF: "PF",
  TF: "TF",
  GA: "GA",
  GM: "GM",
  GE: "GE",
  DE: "DE",
  GH: "GH",
  GI: "GI",
  GR: "GR",
  GL: "GL",
  GD: "GD",
  GP: "GP",
  GU: "GU",
  GT: "GT",
  GG: "GG",
  GN: "GN",
  GW: "GW",
  GY: "GY",
  HT: "HT",
  HM: "HM",
  HN: "HN",
  HK: "HK",
  HU: "HU",
  IS: "IS",
  IN: "IN",
  ID: "ID",
  IR: "IR",
  IQ: "IQ",
  IE: "IE",
  IM: "IM",
  IL: "IL",
  IT: "IT",
  JM: "JM",
  JP: "JP",
  JE: "JE",
  JO: "JO",
  KZ: "KZ",
  KE: "KE",
  KI: "KI",
  KW: "KW",
  KG: "KG",
  LA: "LA",
  LV: "LV",
  LB: "LB",
  LS: "LS",
  LR: "LR",
  LY: "LY",
  LI: "LI",
  LT: "LT",
  LU: "LU",
  MO: "MO",
  MG: "MG",
  MW: "MW",
  MY: "MY",
  MV: "MV",
  ML: "ML",
  MT: "MT",
  MH: "MH",
  MQ: "MQ",
  MR: "MR",
  MU: "MU",
  YT: "YT",
  MX: "MX",
  FM: "FM",
  MD: "MD",
  MC: "MC",
  MN: "MN",
  ME: "ME",
  MS: "MS",
  MA: "MA",
  MZ: "MZ",
  MM: "MM",
  NA: "NA",
  NR: "NR",
  NP: "NP",
  NL: "NL",
  NC: "NC",
  NZ: "NZ",
  NI: "NI",
  NE: "NE",
  NG: "NG",
  NU: "NU",
  NF: "NF",
  KP: "KP",
  MK: "MK",
  MP: "MP",
  NO: "NO",
  OM: "OM",
  PK: "PK",
  PW: "PW",
  PS: "PS",
  PA: "PA",
  PG: "PG",
  PY: "PY",
  PE: "PE",
  PH: "PH",
  PN: "PN",
  PL: "PL",
  PT: "PT",
  PR: "PR",
  QA: "QA",
  RE: "RE",
  RO: "RO",
  RU: "RU",
  RW: "RW",
  BL: "BL",
  SH: "SH",
  KN: "KN",
  LC: "LC",
  MF: "MF",
  PM: "PM",
  VC: "VC",
  WS: "WS",
  SM: "SM",
  ST: "ST",
  SA: "SA",
  SN: "SN",
  RS: "RS",
  SC: "SC",
  SL: "SL",
  SG: "SG",
  SX: "SX",
  SK: "SK",
  SI: "SI",
  SB: "SB",
  SO: "SO",
  ZA: "ZA",
  GS: "GS",
  KR: "KR",
  SS: "SS",
  ES: "ES",
  LK: "LK",
  SD: "SD",
  SR: "SR",
  SJ: "SJ",
  SE: "SE",
  CH: "CH",
  SY: "SY",
  TW: "TW",
  TJ: "TJ",
  TZ: "TZ",
  TH: "TH",
  TL: "TL",
  TG: "TG",
  TK: "TK",
  TO: "TO",
  TT: "TT",
  TN: "TN",
  TR: "TR",
  TM: "TM",
  TC: "TC",
  TV: "TV",
  UG: "UG",
  UA: "UA",
  AE: "AE",
  GB: "GB",
  UM: "UM",
  US: "US",
  UY: "UY",
  UZ: "UZ",
  VU: "VU",
  VA: "VA",
  VE: "VE",
  VN: "VN",
  VG: "VG",
  VI: "VI",
  WF: "WF",
  EH: "EH",
  YE: "YE",
  ZM: "ZM",
  ZW: "ZW",
} as const;

export interface DailyPlan {
  readonly id: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  calories: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  protein: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  fats: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  carbs: number;
  start_date?: string;
  profile: number;
}

export interface DaySummary {
  readonly daily_plan: DailyPlan;
  calories: number;
  protein: number;
  fats: number;
  carbs: number;
  date?: string;
}

export interface DietRecommendations {
  calories: number;
  protein: number;
  fats: number;
  carbs: number;
}

export interface Food {
  readonly id: number;
  /** @maxLength 250 */
  name: string;
  /**
   * @maxLength 13
   * @nullable
   */
  bar_code?: string | null;
  /**
   * @maxLength 150
   * @nullable
   */
  brand?: string | null;
  ingredients?: unknown;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  serving?: number;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  calories?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  fats?: string | null;
  extra_fats_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  carbs?: string | null;
  extra_carbs_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  protein?: string | null;
  is_vegan?: boolean;
  is_vegetarian?: boolean;
  is_gluten_free?: boolean;
}

/**
 * * `breakfast` - Breakfast
 * `lunch` - Lunch
 * `dinner` - Dinner
 * `snack` - snack
 * `extra` - extra
 */
export type FoodTimeEnum = (typeof FoodTimeEnum)[keyof typeof FoodTimeEnum];

export const FoodTimeEnum = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  extra: "extra",
} as const;

export interface FoodLog {
  readonly id: number;
  /** @nullable */
  food_name?: string | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount: string;
  amount_unit?: AmountUnitEnum;
  timestamp: string;
  food_time?: FoodTimeEnum;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  calories?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  fats?: string | null;
  extra_fats_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  carbs?: string | null;
  extra_carbs_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  protein?: string | null;
  profile: number;
  /** @nullable */
  food?: number | null;
}

/**
 * * `male` - Male
 * `female` - Female
 */
export type GenderEnum = (typeof GenderEnum)[keyof typeof GenderEnum];

export const GenderEnum = {
  male: "male",
  female: "female",
} as const;

/**
 * * `weight_loss` - Weight Loss
 * `maintenance` - Maintenance
 * `weight_gain` - Weight Gain
 */
export type GoalEnum = (typeof GoalEnum)[keyof typeof GoalEnum];

export const GoalEnum = {
  weight_loss: "weight_loss",
  maintenance: "maintenance",
  weight_gain: "weight_gain",
} as const;

/**
 * * `conservative` - Conservative
 * `moderate` - Moderate
 * `aggressive` - Aggressive
 */
export type GoalIntensityEnum =
  (typeof GoalIntensityEnum)[keyof typeof GoalIntensityEnum];

export const GoalIntensityEnum = {
  conservative: "conservative",
  moderate: "moderate",
  aggressive: "aggressive",
} as const;

export interface Login {
  username?: string;
  email?: string;
  password: string;
}

export type NullEnum = (typeof NullEnum)[keyof typeof NullEnum];

export const NullEnum = {} as const;

export interface PasswordChange {
  /** @maxLength 128 */
  new_password1: string;
  /** @maxLength 128 */
  new_password2: string;
}

/**
 * Serializer for requesting a password reset e-mail.
 */
export interface PasswordReset {
  email: string;
}

/**
 * Serializer for confirming a password reset attempt.
 */
export interface PasswordResetConfirm {
  /** @maxLength 128 */
  new_password1: string;
  /** @maxLength 128 */
  new_password2: string;
  uid: string;
  token: string;
}

export interface PatchedDailyPlan {
  readonly id?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  calories?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  protein?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  fats?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  carbs?: number;
  start_date?: string;
  profile?: number;
}

export interface PatchedFood {
  readonly id?: number;
  /** @maxLength 250 */
  name?: string;
  /**
   * @maxLength 13
   * @nullable
   */
  bar_code?: string | null;
  /**
   * @maxLength 150
   * @nullable
   */
  brand?: string | null;
  ingredients?: unknown;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  serving?: number;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  calories?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  fats?: string | null;
  extra_fats_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  carbs?: string | null;
  extra_carbs_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  protein?: string | null;
  is_vegan?: boolean;
  is_vegetarian?: boolean;
  is_gluten_free?: boolean;
}

export interface PatchedFoodLog {
  readonly id?: number;
  /** @nullable */
  food_name?: string | null;
  /** @pattern ^-?\d{0,8}(?:\.\d{0,2})?$ */
  amount?: string;
  amount_unit?: AmountUnitEnum;
  timestamp?: string;
  food_time?: FoodTimeEnum;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  calories?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  fats?: string | null;
  extra_fats_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  carbs?: string | null;
  extra_carbs_info?: unknown;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  protein?: string | null;
  profile?: number;
  /** @nullable */
  food?: number | null;
}

/**
 * * `kg` - kg
 * `lb` - lb
 */
export type WeightUnitEnum =
  (typeof WeightUnitEnum)[keyof typeof WeightUnitEnum];

export const WeightUnitEnum = {
  kg: "kg",
  lb: "lb",
} as const;

export interface PatchedProfile {
  readonly id?: number;
  readonly daily_plan?: DailyPlan;
  /** @maxLength 250 */
  name?: string;
  birth_date?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  height?: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  weight_value?: number;
  weight_unit?: WeightUnitEnum;
  /**
   * @minimum 1.2
   * @maximum 1.9
   */
  activity_degree?: number;
  goal?: GoalEnum;
  goal_intensity?: GoalIntensityEnum | BlankEnum | NullEnum;
  gender?: GenderEnum;
  country?: CountryEnum | BlankEnum | NullEnum;
}

/**
 * User model w/o password
 */
export interface PatchedUserDetails {
  readonly pk?: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username?: string;
  readonly email?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
}

export interface Profile {
  readonly id: number;
  readonly daily_plan: DailyPlan;
  /** @maxLength 250 */
  name: string;
  birth_date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  height: number;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  weight_value: number;
  weight_unit?: WeightUnitEnum;
  /**
   * @minimum 1.2
   * @maximum 1.9
   */
  activity_degree: number;
  goal?: GoalEnum;
  goal_intensity?: GoalIntensityEnum | BlankEnum | NullEnum;
  gender: GenderEnum;
  country?: CountryEnum | BlankEnum | NullEnum;
}

export interface Register {
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
  email: string;
  password1: string;
  password2: string;
}

export interface ResendEmailVerification {
  email: string;
}

export interface RestAuthDetail {
  readonly detail: string;
}

/**
 * Serializer for Token model.
 */
export interface Token {
  /** @maxLength 40 */
  key: string;
}

/**
 * User model w/o password
 */
export interface UserDetails {
  readonly pk: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  readonly email: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
}

export interface VerifyEmail {
  key: string;
}

export type FoodLogListParams = {
  date?: string;
  profile?: number;
};

export type FoodLogDaySummaryRetrieveParams = {
  date?: string;
  profile: number;
};

export type FoodLogDaySummaryRangeListParams = {
  date?: string;
  end?: string;
  last_days?: number;
  profile?: number;
  start?: string;
};

/**
 * Unspecified response body
 */
export type ProfileUpdateDailyPlanUpdate400 = { [key: string]: unknown };

/**
 * Unspecified response body
 */
export type ProfileUpdateDailyPlanPartialUpdate400 = { [key: string]: unknown };
